export const PROBLEMS = [
  "K Closest Points to Origin",
  "Sort Colors",
  "Inorder Successor in BST",
  "Number of Islands",
  "Implement Queue using Stacks",
  "Design Hit Counter",
  "Symmetric Tree",
  "Top K Frequent Words",
  "Find the Duplicate Number",
  "Largest Number",
  "Two Sum",
  "Flood Fill",
  "Daily Temperatures",
  "Design Add and Search Words Data Structure",
  "Reorder List",
  "Find the Index of the First Occurrence in a String",
  "Insert Interval",
  "Add Two Numbers",
  "LRU Cache",
  "Climbing Stairs",
  "Course Schedule",
  "01 Matrix",
  "Accounts Merge",
  "Random Pick with Weight",
  "Valid Parentheses",
  "Construct Binary Tree from Preorder and Inorder Traversal",
  "Add Binary",
  "Longest Consecutive Sequence",
  "Sqrt(x)",
  "Permutations",
  "Generate Parentheses",
  "Reverse Linked List",
  "Swap Nodes in Pairs",
  "Word Search",
  "Number of 1 Bits",
  "Contiguous Array",
  "Balanced Binary Tree",
  "Validate Binary Search Tree",
  "Remove Duplicates from Sorted Array",
  "3Sum Closest",
  "Minimum Knight Moves",
  "Lowest Common Ancestor of a Binary Search Tree",
  "Contains Duplicate",
  "Longest Palindromic Substring",
  "Binary Tree Zigzag Level Order Traversal",
  "Container With Most Water",
  "Meeting Rooms",
  "Diameter of Binary Tree",
  "Merge Sorted Array",
  "Word Pattern",
  "Palindrome Linked List",
  "Merge Two Sorted Lists",
  "Maximum Product Subarray",
  "Reverse Bits",
  "Group Anagrams",
  "Remove Nth Node From End of List",
  "Best Time to Buy and Sell Stock",
  "Single Number",
  "Valid Palindrome",
  "Number of Connected Components in an Undirected Graph",
  "House Robber",
  "Subtree of Another Tree",
  "Kth Largest Element in an Array",
  "Backspace String Compare",
  "Unique Paths",
  "Combination Sum",
  "Spiral Matrix",
  "String to Integer (atoi)",
  "Search in Rotated Sorted Array",
  "Evaluate Reverse Polish Notation",
  "Rotate Image",
  "Path Sum III",
  "Time Based Key-Value Store",
  "Basic Calculator II",
  "Invert Binary Tree",
  "Non-overlapping Intervals",
  "Pow(x, n)",
  "Maximum Subarray",
  "Pacific Atlantic Water Flow",
  "Min Stack",
  "Jump Game",
  "Roman to Integer",
  "Rotting Oranges",
  "Gas Station",
  "Search a 2D Matrix",
  "Decode String",
  "Maximum Width of Binary Tree",
  "Ransom Note",
  "Valid Anagram",
  "Sort List",
  "Subsets",
  "Minimum Height Trees",
  "Asteroid Collision",
  "Summary Ranges",
  "Coin Change",
  "First Bad Version",
  "Shortest Path to Get Food",
  "Majority Element",
  "Find All Anagrams in a String",
  "Longest Common Prefix",
  "Longest Palindrome",
  "Course Schedule II",
  "Move Zeroes",
  "Implement Trie (Prefix Tree)",
  "Encode and Decode Strings",
  "Combination Sum IV",
  "Find K Closest Elements",
  "Graph Valid Tree",
  "Binary Tree Right Side View",
  "Is Subsequence",
  "Partition Equal Subset Sum",
  "Task Scheduler",
  "Squares of a Sorted Array",
  "Longest Substring Without Repeating Characters",
  "Binary Search",
  "Meeting Rooms II",
  "Same Tree",
  "Letter Combinations of a Phone Number",
  "Palindrome Number",
  "Convert Sorted Array to Binary Search Tree",
  "Path Sum II",
  "Valid Sudoku",
  "Linked List Cycle",
  "Kth Smallest Element in a BST",
  "3Sum",
  "Rotate Array",
  "Odd Even Linked List",
  "Binary Tree Level Order Traversal",
  "Subarray Sum Equals K",
  "Isomorphic Strings",
  "Word Break",
  "Longest Increasing Subsequence",
  "Next Permutation",
  "Search Insert Position",
  "Merge Intervals",
  "Maximum Depth of Binary Tree",
  "Insert Delete GetRandom O(1)",
  "Length of Last Word",
  "Middle of the Linked List",
  "Reverse Integer",
  "Minimum Absolute Difference in BST",
  "Missing Number",
  "Counting Bits",
  "Find Minimum in Rotated Sorted Array",
  "Product of Array Except Self",
  "Lowest Common Ancestor of a Binary Tree",
  "Average of Levels in Binary Tree",
  "Remove Element",
  "Decode Ways",
  "Contains Duplicate II",
  "Maximal Square",
  "Cheapest Flights Within K Stops",
  "All Nodes Distance K in Binary Tree",
  "Happy Number",
  "Plus One",
  "Path Sum",
  "Rotate List",
  "Set Matrix Zeroes",
  "Longest Repeating Character Replacement",
  "Clone Graph",
];
